version: "3.7"

services:
  nginx:
    build:
      context: ./requirements/nginx
    restart: on-failure
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/html
      - ./requirements/nginx/ssl:/etc/nginx/ssl
    networks:
      - bridge_inception

  wordpress: 
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    restart: on-failure
    depends_on:
      - mariadb
    ports:
      - "9000:9000"
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - bridge_inception
    secrets:
      - mysql_root_password
      - mysql_user
      - mysql_password
      - mysql_database

  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./secrets:/run/secrets
    networks:
      - bridge_inception
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      retries: 3
      start_period: 5s
      timeout: 10s
    secrets:
      - mysql_root_password
      - mysql_user
      - mysql_password
      - mysql_database

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/data/mariadb
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/data/wordpress
    
secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password
  mysql_user:
    file: ./secrets/mysql_user
  mysql_password:
    file: ./secrets/mysql_password
  mysql_database:
    file: ./secrets/mysql_database

networks:
  bridge_inception:
    driver: bridge
