#!/bin/bash

service mysql start

sleep 1

echo $MYSQL_ROOT_PASSWORD
echo $MYSQL_USER
echo $MYSQL_PASSWORD
echo $MYSQL_DATABASE
mysql <<EOF
CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE;
CREATE USER IF NOT EXISTS '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO '$MYSQL_USER'@'%';
ALTER USER 'root'@'localhost' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD';
FLUSH PRIVILEGES;
EOF

kill $(cat /var/run/mysqld/mysqld.pid)

mysqld